# Symbolic Approach


In [1]:
from sympy import * 
import matplotlib.pyplot as plt
import scipy as sp
from scipy import linalg
init_printing(use_latex='mathjax')
%matplotlib inline

## Vandermonde normalized special

In [9]:
a,b,c,d = symbols(r'a,b,c,d')
x,y,x00, y00, x10, y10, x01, y01, x11, y11 = symbols(r'x,y,x_{i\text{\,}j}, y_{i\text{\,}j}, x_{i+1\text{\,}j},\
y_{i+1\text{\,}j}, x_{i\text{\,}j+1}, y_{i\text{\,}j+1}, x_{i+1\text{\,}j+1}, y_{i+1\text{\,}j+1}')

In [19]:
Vandermonde = Matrix([[1, x00,y00,x00*y00],
                      [1, x10,y10,x10*y10],
                      [1, x01,y01,x01*y01],
                      [1, x11,y11,x11*y11]])           
Vandermonde

⎡1    x_{i\text{,}j}      y_{i\text{,}j}        x_{i\text{,}j}⋅y_{i\text{,}j} 
⎢                                                                             
⎢1   x_{i+1\text{,}j}    y_{i+1\text{,}j}     x_{i+1\text{,}j}⋅y_{i+1\text{,}j
⎢                                                                             
⎢1   x_{i\text{,}j+1}    y_{i\text{,}j+1}     x_{i\text{,}j+1}⋅y_{i\text{,}j+1
⎢                                                                             
⎣1  x_{i+1\text{,}j+1}  y_{i+1\text{,}j+1}  x_{i+1\text{,}j+1}⋅y_{i+1\text{,}j

   ⎤
   ⎥
}  ⎥
   ⎥
}  ⎥
   ⎥
+1}⎦

In [13]:
print latex(Vandermonde)

\left[\begin{matrix}1 & x_{i\text{,}j} & y_{i\text{,}j} & x_{i\text{,}j} y_{i\text{,}j}\\1 & x_{i+1\text{,}j} & y_{i+1\text{,}j} & x_{i+1\text{,}j} y_{i+1\text{,}j}\\1 & x_{i\text{,}j+1} & y_{i\text{,}j+1} & x_{i\text{,}j+1} y_{i\text{,}j+1}\\1 & x_{i+1\text{,}j+1} & y_{i+1\text{,}j+1} & x_{i+1\text{,}j+1} y_{i+1\text{,}j+1}\end{matrix}\right]


In [5]:
a,b,c,d = symbols(r'a,b,c,d')
x,y,dx00, dy00, dx10, dy10, dx01, dy01, dx11, dy11 = symbols(r'x,y,dx00, dy00, dx10, dy10, dx01, dy01, dx11, dy11')

f00, f10, f01, f11 = symbols(r'f00, f10, f01, f11')

Vandermonde = Matrix([[1, 0,0,0],
           [1, 1, (dy10-dy00)/(dy01-dy00), (dy10-dy00)/(dy01-dy00)],
           [1, (dx01-dx00)/(dx10-dx00),1 ,(dx01-dx00)/(dx10-dx00)],
           [1,(dx11-dx00)/(dx10-dx00), (dy11-dy00)/(dy01-dy00), (dy11-dy00)/(dy01-dy00)*(dx11-dx00)/(dx10-dx00)]])



In [4]:
Vandermonde

⎡1       0             0                      0              ⎤
⎢                                                            ⎥
⎢                 -dy₀₀ + dy₁₀          -dy₀₀ + dy₁₀         ⎥
⎢1       1        ────────────          ────────────         ⎥
⎢                 -dy₀₀ + dy₀₁          -dy₀₀ + dy₀₁         ⎥
⎢                                                            ⎥
⎢   -dx₀₀ + dx₀₁                        -dx₀₀ + dx₀₁         ⎥
⎢1  ────────────       1                ────────────         ⎥
⎢   -dx₀₀ + dx₁₀                        -dx₀₀ + dx₁₀         ⎥
⎢                                                            ⎥
⎢   -dx₀₀ + dx₁₁  -dy₀₀ + dy₁₁  (-dx₀₀ + dx₁₁)⋅(-dy₀₀ + dy₁₁)⎥
⎢1  ────────────  ────────────  ─────────────────────────────⎥
⎣   -dx₀₀ + dx₁₀  -dy₀₀ + dy₀₁  (-dx₀₀ + dx₁₀)⋅(-dy₀₀ + dy₀₁)⎦

In [6]:
Vector = Matrix([1,(x-dx00)/(dx10-dx00),(y-dy00)/(dy01-dy00),(x-dx00)/(dx10-dx00)*(y-dy00)/(dy01-dy00)])
Vector

⎡              1              ⎤
⎢                             ⎥
⎢         -dx₀₀ + x           ⎥
⎢        ────────────         ⎥
⎢        -dx₀₀ + dx₁₀         ⎥
⎢                             ⎥
⎢         -dy₀₀ + y           ⎥
⎢        ────────────         ⎥
⎢        -dy₀₀ + dy₀₁         ⎥
⎢                             ⎥
⎢   (-dx₀₀ + x)⋅(-dy₀₀ + y)   ⎥
⎢─────────────────────────────⎥
⎣(-dx₀₀ + dx₁₀)⋅(-dy₀₀ + dy₀₁)⎦

In [8]:
V1 =Vandermonde.inverse_ADJ()
V1 = V1.T

In [32]:
VD = V1*Vector
VD = simplify(VD)

In [34]:
VD

⎡                                                                             
⎢                                                   ──────────────────────────
⎢                                                   dx₀₀⋅dx₀₁⋅dy₀₀⋅dy₁₀ - dx₀₀
⎢                                                                             
⎢                                                                             
⎢  ───────────────────────────────────────────────────────────────────────────
⎢  (dx₀₀ - dx₁₀)⋅(3⋅(dx₀₀ - dx₀₁)⋅(dx₀₀ - dx₁₀)⋅(dy₀₀ - dy₁₁)⋅(2⋅dy₀₀ - dy₀₁ -
⎢                                                                             
⎢                                                                             
⎢─────────────────────────────────────────────────────────────────────────────
⎢(dy₀₀ - dy₀₁)⋅(3⋅(dx₀₀ - dx₀₁)⋅(dx₀₀ - dx₁₀)⋅(dy₀₀ - dy₁₁)⋅(-2⋅dy₀₀ + dy₀₁ + 
⎢                                                                             
⎢                                                   

In [22]:
len(VD)

4

In [5]:
a, b, c, d = symbols(r'a, b, c, d')
Vandermonde2 = Matrix([[1, 0,0,0],
           [1, 1, a, a],
           [1, b,1 ,b],
           [1,c, d, c*d]])


In [ ]:
a  = (dy10-dy00)/(dy01-dy00);
b  = (dx01-dx00)/(dx10-dx00);
c  = (dx11-dx00)/(dx10-dx00);
d  = (dy11-dy00)/(dy01-dy00);

In [9]:
V2 = Vandermonde2.inverse_ADJ()
V2 = simplify(V2)
V2 = V2.T
V2

⎡       a⋅b - a⋅c⋅d + a⋅d - a - b⋅d + c⋅d          a⋅b - a⋅c - b⋅c⋅d + b⋅c - b
⎢1  ─────────────────────────────────────────  ───────────────────────────────
⎢   a⋅b⋅c⋅d - a⋅b⋅c - a⋅b⋅d + a⋅c + b⋅d - c⋅d  a⋅b⋅c⋅d - a⋅b⋅c - a⋅b⋅d + a⋅c +
⎢                                                                             
⎢                   d⋅(b - c)                                 b⋅c⋅(d - 1)     
⎢0  ─────────────────────────────────────────  ───────────────────────────────
⎢   a⋅b⋅c⋅d - a⋅b⋅c - a⋅b⋅d + a⋅c + b⋅d - c⋅d  a⋅b⋅c⋅d - a⋅b⋅c - a⋅b⋅d + a⋅c +
⎢                                                                             
⎢                  a⋅d⋅(c - 1)                                 c⋅(a - d)      
⎢0  ─────────────────────────────────────────  ───────────────────────────────
⎢   a⋅b⋅c⋅d - a⋅b⋅c - a⋅b⋅d + a⋅c + b⋅d - c⋅d  a⋅b⋅c⋅d - a⋅b⋅c - a⋅b⋅d + a⋅c +
⎢                                                                             
⎢                  -a⋅(b - 1)                       

In [10]:
for i in range(0,4):
    for j in range(0,4):
        print "Interpolation_Coeff[%i][%i]= %s; "%(i,j,printing.ccode(V2[i,j]))

Interpolation_Coeff[0][0]= 1; 
Interpolation_Coeff[0][1]= (a*b - a*c*d + a*d - a - b*d + c*d)/(a*b*c*d - a*b*c - a*b*d + a*c + b*d - c*d); 
Interpolation_Coeff[0][2]= (a*b - a*c - b*c*d + b*c - b + c*d)/(a*b*c*d - a*b*c - a*b*d + a*c + b*d - c*d); 
Interpolation_Coeff[0][3]= (-a*b + a*c + b*d - c - d + 1)/(a*b*c*d - a*b*c - a*b*d + a*c + b*d - c*d); 
Interpolation_Coeff[1][0]= 0; 
Interpolation_Coeff[1][1]= d*(b - c)/(a*b*c*d - a*b*c - a*b*d + a*c + b*d - c*d); 
Interpolation_Coeff[1][2]= b*c*(d - 1)/(a*b*c*d - a*b*c - a*b*d + a*c + b*d - c*d); 
Interpolation_Coeff[1][3]= (-b*d + c)/(a*b*c*d - a*b*c - a*b*d + a*c + b*d - c*d); 
Interpolation_Coeff[2][0]= 0; 
Interpolation_Coeff[2][1]= a*d*(c - 1)/(a*b*c*d - a*b*c - a*b*d + a*c + b*d - c*d); 
Interpolation_Coeff[2][2]= c*(a - d)/(a*b*c*d - a*b*c - a*b*d + a*c + b*d - c*d); 
Interpolation_Coeff[2][3]= (-a*c + d)/(a*b*c*d - a*b*c - a*b*d + a*c + b*d - c*d); 
Interpolation_Coeff[3][0]= 0; 
Interpolation_Coeff[3][1]= -a*(b - 1)/(a*b*c*d - a

## Vandermonde

In [2]:
a,b,c,d = symbols(r'a,b,c,d')
dx00, dy00, dx10, dy10, dx01, dy01, dx11, dy11 = symbols(r'dx00, dy00, dx10, dy10, dx01, dy01, dx11, dy11')
f00, f10, f01, f11 = symbols(r'f00, f10, f01, f11')


In [3]:
Vandermonde = Matrix([[dx10, dy10, dx10*dy10],
           [dx01, dy01, dx01*dy01],
           [dx11, dy11, dx11*dy11]])
B = Matrix([a,b,c])
C = Matrix([f10-f00,f01-f00,f11-f00])

In [4]:

Vandermonde,B,C


⎛⎡dx₁₀  dy₁₀  dx₁₀⋅dy₁₀⎤, ⎡a⎤, ⎡-f₀₀ + f₁₀⎤⎞
⎜⎢                     ⎥  ⎢ ⎥  ⎢          ⎥⎟
⎜⎢dx₀₁  dy₀₁  dx₀₁⋅dy₀₁⎥  ⎢b⎥  ⎢-f₀₀ + f₀₁⎥⎟
⎜⎢                     ⎥  ⎢ ⎥  ⎢          ⎥⎟
⎝⎣dx₁₁  dy₁₁  dx₁₁⋅dy₁₁⎦  ⎣c⎦  ⎣-f₀₀ + f₁₁⎦⎠

## LU decomposition

In [6]:
#k,b,c,d = symbols(r'a,b,c,d')
Vandermonde.LUdecomposition()

⎛⎡ 1            0           0⎤, ⎡dx₁₀         dy₁₀                            
⎜⎢                           ⎥  ⎢                                             
⎜⎢dx₀₁                       ⎥  ⎢        dx₀₁⋅dy₁₀                            
⎜⎢────          1           0⎥  ⎢ 0    - ───────── + dy₀₁                     
⎜⎢dx₁₀                       ⎥  ⎢           dx₁₀                              
⎜⎢                           ⎥  ⎢                                             
⎜⎢              dx₁₁⋅dy₁₀    ⎥  ⎢                                             
⎜⎢       dy₁₁ - ─────────    ⎥  ⎢                                             
⎜⎢dx₁₁             dx₁₀      ⎥  ⎢                                             
⎜⎢────  ──────────────────  1⎥  ⎢ 0            0           -dx₁₁⋅dy₁₀ + dx₁₁⋅d
⎜⎢dx₁₀    dx₀₁⋅dy₁₀          ⎥  ⎢                                             
⎜⎢      - ───────── + dy₀₁   ⎥  ⎢                                             
⎝⎣           dx₁₀            ⎦  ⎣                   

In [8]:
print latex(Vandermonde.LUdecomposition())

\left ( \left[\begin{matrix}1 & 0 & 0\\\frac{dx_{01}}{dx_{10}} & 1 & 0\\\frac{dx_{11}}{dx_{10}} & \frac{dy_{11} - \frac{dx_{11} dy_{10}}{dx_{10}}}{- \frac{dx_{01} dy_{10}}{dx_{10}} + dy_{01}} & 1\end{matrix}\right], \quad \left[\begin{matrix}dx_{10} & dy_{10} & dx_{10} dy_{10}\\0 & - \frac{dx_{01} dy_{10}}{dx_{10}} + dy_{01} & dx_{01} dy_{01} - dx_{01} dy_{10}\\0 & 0 & - dx_{11} dy_{10} + dx_{11} dy_{11} - \frac{\left(dy_{11} - \frac{dx_{11} dy_{10}}{dx_{10}}\right) \left(dx_{01} dy_{01} - dx_{01} dy_{10}\right)}{- \frac{dx_{01} dy_{10}}{dx_{10}} + dy_{01}}\end{matrix}\right], \quad \left [ \right ]\right )


## Adjuagate Inverse

In [14]:
dx00, dy00, dx10, dy10, dx01, dy01, dx11, dy11 = symbols(r'dx00, dy00, dx10, dy10, dx01, dy01, dx11, dy11')
Vandermonde = Matrix([[dx10, dy10, dx10*dy10],
[dx01, dy01, dx01*dy01],
[dx11, dy11, dx11*dy11]])
Vandermonde[1,0] = 0
Vandermonde[1,2] = 0
#Vandermonde[0,1] = 0
#Vandermonde[0,2] = 0
Vandermonde

⎡dx₁₀  dy₁₀  dx₁₀⋅dy₁₀⎤
⎢                     ⎥
⎢ 0    dy₀₁      0    ⎥
⎢                     ⎥
⎣dx₁₁  dy₁₁  dx₁₁⋅dy₁₁⎦

In [15]:
V1 = Vandermonde.inverse_ADJ()
V1

⎡                            dx₁₁⋅dy₀₁⋅dy₁₁                                   
⎢─────────────────────────────────────────────────────────────────────  ──────
⎢    2                                                                      2 
⎢dx₁₀ ⋅dx₁₁⋅dy₁₀ + dx₁₀⋅dx₁₁⋅dy₀₁⋅dy₁₁ + dx₁₀⋅dx₁₁⋅dy₁₀⋅(-dx₁₀ - dy₀₁)  dx₁₀ ⋅
⎢                                                                             
⎢                                                                             
⎢                                  0                                    ──────
⎢                                                                           2 
⎢                                                                       dx₁₀ ⋅
⎢                                                                             
⎢                             -dx₁₁⋅dy₀₁                                      
⎢─────────────────────────────────────────────────────────────────────  ──────
⎢    2                                              

In [16]:
simplify(Vandermonde*V1)

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

In [17]:
V1 = Vandermonde.inverse_ADJ()
V1

⎡                            dx₁₁⋅dy₀₁⋅dy₁₁                                   
⎢─────────────────────────────────────────────────────────────────────  ──────
⎢    2                                                                      2 
⎢dx₁₀ ⋅dx₁₁⋅dy₁₀ + dx₁₀⋅dx₁₁⋅dy₀₁⋅dy₁₁ + dx₁₀⋅dx₁₁⋅dy₁₀⋅(-dx₁₀ - dy₀₁)  dx₁₀ ⋅
⎢                                                                             
⎢                                                                             
⎢                                  0                                    ──────
⎢                                                                           2 
⎢                                                                       dx₁₀ ⋅
⎢                                                                             
⎢                             -dx₁₁⋅dy₀₁                                      
⎢─────────────────────────────────────────────────────────────────────  ──────
⎢    2                                              

In [18]:
for i in range(0,3):
    for j in range(0,3):
        print "coeff[%i][%i]= %s; "%(i,j,printing.ccode(V1[i,j]))

coeff[0][0]= dx11*dy01*dy11/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 
coeff[0][1]= (dx10*dy10*dy11 - dx11*dy10*dy11)/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 
coeff[0][2]= -dx10*dy01*dy10/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 
coeff[1][0]= 0; 
coeff[1][1]= (-dx10*dx11*dy10 + dx10*dx11*dy11)/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 
coeff[1][2]= 0; 
coeff[2][0]= -dx11*dy01/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 
coeff[2][1]= (-dx10*dy11 + dx11*dy10)/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 
coeff[2][2]= dx10*dy01/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 


In [21]:
f00  = 10
f10  = 12
f11  = -2
f01  = -1
A= sp.zeros((3,3))

I= sp.zeros((3,3))
A = sp.array([[2.6316 ,  -16138.6  , -42470.4],
[0 ,  7380.77  , 0],
[2.6316 ,  -9111.06  , -23976.7]
])

I[0][0] = 1
I[1][1] = 1
I[2][2] = 1


print A

print sp.linalg.inv(A)
AO = sp.copy(A)
Matrix(A).inverse_ADJ()

[[  2.63160000e+00  -1.61386000e+04  -4.24704000e+04]
 [  0.00000000e+00   7.38077000e+03   0.00000000e+00]
 [  2.63160000e+00  -9.11106000e+03  -2.39767000e+04]]
[[ -4.92658209e-01  -2.22601163e-08   8.72655169e-01]
 [  0.00000000e+00   1.35487219e-04  -0.00000000e+00]
 [ -5.40724679e-05  -5.14846596e-05   5.40724679e-05]]


⎡ -0.492658208547511   -2.22601161923755e-8   0.872655168571831 ⎤
⎢                                                               ⎥
⎢         0            0.000135487218813213           0         ⎥
⎢                                                               ⎥
⎣-5.40724679215084e-5  -5.14846596245537e-5  5.40724679215084e-5⎦

In [20]:
V1 = Vandermonde.inverse_ADJ()
s = []
for i in range(0,3):
    for j in range(0,3):
        s.append("%s; "%(printing.ccode(V1[i,j])))

        
ndx10 = A[0][0]
ndy10 = A[0][1] 

ndx01 = A[1][0] 
ndy01 = A[1][1]

ndx11= A[2][0]
ndy11= A[2][1]
for ss in s:
    ss.replace('dx10',str(ndx10))
    ss.replace('dx01',str(ndx01))
    ss.replace('dx11',str(ndx11))
    ss.replace('dy10',str(ndy10))
    ss.replace('dy01',str(ndy01))
    ss.replace('dy11',str(ndy11))
    print ss
    


dx11*dy01*dy11/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 
(dx10*dy10*dy11 - dx11*dy10*dy11)/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 
-dx10*dy01*dy10/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 
0; 
(-dx10*dx11*dy10 + dx10*dx11*dy11)/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 
0; 
-dx11*dy01/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 
(-dx10*dy11 + dx11*dy10)/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 
dx10*dy01/(pow(dx10, 2)*dx11*dy10 + dx10*dx11*dy01*dy11 + dx10*dx11*dy10*(-dx10 - dy01)); 


In [91]:
s

['(-dx01*dy01*dy11 + dx11*dy01*dy11)/(dx11*dy11*(-dx01*dy10 + dx10*dy01) + dx11*(dx01*dy01*dy10 + pow(dx10, 2)*dy10) + dy11*(dx01*dx10*dy10 + dx01*pow(dy01, 2)) - (-dx10 - dy01)*(-dx01*dy01*dy11 - dx10*dx11*dy10)); ',
 '(dx10*dy10*dy11 - dx11*dy10*dy11)/(dx11*dy11*(-dx01*dy10 + dx10*dy01) + dx11*(dx01*dy01*dy10 + pow(dx10, 2)*dy10) + dy11*(dx01*dx10*dy10 + dx01*pow(dy01, 2)) - (-dx10 - dy01)*(-dx01*dy01*dy11 - dx10*dx11*dy10)); ',
 '(dx01*dy01*dy10 - dx10*dy01*dy10)/(dx11*dy11*(-dx01*dy10 + dx10*dy01) + dx11*(dx01*dy01*dy10 + pow(dx10, 2)*dy10) + dy11*(dx01*dx10*dy10 + dx01*pow(dy01, 2)) - (-dx10 - dy01)*(-dx01*dy01*dy11 - dx10*dx11*dy10)); ',
 '(dx01*dx11*dy01 - dx01*dx11*dy11)/(dx11*dy11*(-dx01*dy10 + dx10*dy01) + dx11*(dx01*dy01*dy10 + pow(dx10, 2)*dy10) + dy11*(dx01*dx10*dy10 + dx01*pow(dy01, 2)) - (-dx10 - dy01)*(-dx01*dy01*dy11 - dx10*dx11*dy10)); ',
 '(-dx10*dx11*dy10 + dx10*dx11*dy11)/(dx11*dy11*(-dx01*dy10 + dx10*dy01) + dx11*(dx01*dy01*dy10 + pow(dx10, 2)*dy10) + dy11*(dx01*d

In [1]:
LUT_inverse = sp.array([[-0.49959 ,  0  , 0.8596],
              [0 ,  0.000104827  , -0],
              [-4.03e-05 ,  -3.77388e-05  , 4.03e-05]])
print "Identity test"
test =sp.dot(LUT_inverse,AO)
plt.imshow(test)
test


NameError: name 'sp' is not defined

In [26]:
sp.dot(sp.array(Matrix(A).inverse_ADJ()),AO)

array([[1.00000000000000, 0, 0],
       [0, 1.00000000000000, 0],
       [0, 5.55111512312578e-17, 1.00000000000000]], dtype=object)